// Mocks generated by Mockito 5.2.0 from annotations
// in workspace/test/accounts/account_repo_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:workspace/models/accountList/accounts_main.dart' as _i2;

import 'account_repo_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAccountsMain_0 extends _i1.Fake implements _i2.AccountsMain {}

/// A class which mocks [AccountRepoTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepoTest extends _i1.Mock implements _i3.AccountRepoTest {
  MockAccountRepoTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AccountsMain> fetchAccountList() => (super.noSuchMethod(
          Invocation.method(#fetchAccountList, []),
          returnValue: Future<_i2.AccountsMain>.value(_FakeAccountsMain_0()))
      as _i4.Future<_i2.AccountsMain>);
}
